### ISSUE TITLE
検索結果の画像リンク

### ISSUE THREAD

**Issue by kuroetky** [kuroetky/vue_sample#26]
画像リンクは別タブもしくは別ページで表示する
（同じウィンドウ内でページ遷移すると、戻るボタンで戻ってきたときに結果がなくなっているため）

**Comment by aiit-ryota-nakashima** [comment]
画像リンクのaタグ内にtarget="_blank"を記述すればいけそうですね。

**Comment by aiit-ryota-nakashima** [comment]
別タブで表示するようにしてみました

**Comment by aiit-ryota-nakashima** [comment]
namashima_workブランチからmasterブランチにプルリクエストを投げました。
masterにマージされたらクローズします。

**Comment by kuroetky** [comment]
プルリクのマージ後、リンクをアイコンに変更しておきました。
（見やすいと思ったので）
本件、完了したのでクローズとします。
