### ISSUE TITLE
YouTube Data API実行時にリクエストがcancelledになる原因調査

### ISSUE THREAD

**Issue by aiit-ryota-nakashima** [kuroetky/vue_sample#3]
ローカルファイル(file://~)上において、axiosを利用してYouTube Data APIを実行すると、リクエストがcancelledとなり、jsonデータを取得できない。

**Comment by aiit-ryota-nakashima** [comment]
どうやらinputタグとbuttonをformタグでくくっているのが悪いらしい。
なぜダメなのかは今のところ不明。
<img width="1440" alt="スクリーンショット 2020-08-07 0 32 12" src="https://user-images.githubusercontent.com/65063110/89551407-dff5ea80-d845-11ea-84b7-f73879259375.png">

**Comment by kuroetky** [comment]
動作しているのでクローズします。
