### ISSUE TITLE
ソート機能の実装方法の検討

### ISSUE THREAD

**Issue by aiit-ryota-nakashima** [kuroetky/vue_sample#30]

**Comment by aiit-ryota-nakashima** [comment]
とりあえず実装してみました。
https://github.com/kuroetky/vue_sample/pull/36

**Comment by aiit-ryota-nakashima** [comment]
ラジオボタンを選択リストに変更し、昇順と降順を選択できるように変更しました。
現在は毎回APIを叩いているので、キーワードが同じ場合はAPIを叩かずに並び替えるように実装する予定です。

**Comment by kuroetky** [comment]
本機能は実装が確認できているのでクローズします。
