### ISSUE TITLE
amazonでの商品検索方法の検討

### ISSUE THREAD

**Issue by aiit-ryota-nakashima** [kuroetky/vue_sample#32]
amazonでのグッズ検索のリンクとして
`https://www.amazon.co.jp/s?k={チャンネル名}`
を挿入した。
ただチャンネル名のみでの検索だと、欲しい商品の情報が返ってこないのでそれをどう対応するかを検討する。

以下の二つは本来であれば、同じような結果を返すのが正しい気がする(同YouTuberなので)。
例)
「HikakinTV」での検索結果
<img width="1440" alt="スクリーンショット 2020-08-13 3 10 19" src="https://user-images.githubusercontent.com/65063110/90051384-92302500-dd12-11ea-8228-9a2a899967ee.png">

「HIKAKIN」での検索結果
<img width="1440" alt="スクリーンショット 2020-08-13 3 11 21" src="https://user-images.githubusercontent.com/65063110/90051467-b1c74d80-dd12-11ea-8106-0f0d23aea8a0.png">

**Comment by aiit-ryota-nakashima** [comment]
チャンネル名でそのまま検索するのは今回は良しとする。

**Comment by aiit-ryota-nakashima** [comment]
amazonで絵文字や記号が入っていても正常に検索できるので、特にフィルタリングしなくても良さそう

**Comment by kuroetky** [comment]
アマゾンの検索で記号を含む単語の検索が可能なのでこちらで正規表現は実装しないことにしました。
よって本件はクローズします。
