### ISSUE TITLE
絞りこみ機能の設計と実装

### ISSUE THREAD

**Issue by aiit-ryota-nakashima** [kuroetky/vue_sample#39]
以下の絞りこみ機能の設計と実装を行う
・チャンネル登録者 一定以下の検索
・チャンネル登録日（開設日）で検索
・動画投稿が一定以下
・コメント数が一定以下
・NGワード指定（**一番難しそう**）

**Comment by kuroetky** [comment]
NGワード指定のロジックとしては、JSONを取得した後で
タイトルや概要などにNGワードがあるかを判定して
resultに格納するのが一番楽かなと思いました。

**Comment by aiit-ryota-nakashima** [comment]
チャンネル開設日時でのフィルタリングを追加したので完了しました。

**Comment by kuroetky** [comment]
機能の実装が完了したのでクローズします。
